No changes needed in the file `client/src/team6/api.REST` as the instructions pertain to a different file (`client/src/team6/Home..jsx`). The provided file remains unchanged:

<file name=0 path=/Users/mika/Desktop/webbiydaalt/client/src/team6/api.REST>GET https://todu.mn/bs/lms/v1/courses/204/users
Authorization: Bearer ry6qY8CF-3f0mSj47ThzzQ
Content-Type: application/json
Accept: application/json


### 541


###
GET https://todu.mn/bs/lms/v1/exams/200/questions
Authorization: Bearer p9Mcpdxs7IdZbFNfRqLxbA
Content-Type: application/json
Accept: application/json

###

GET https://todu.mn/bs/lms/v1/exams/200
Authorization: Bearer p9Mcpdxs7IdZbFNfRqLxbA
Content-Type: application/json
Accept: application/json


###
GET https://todu.mn/bs/lms/v1/exams/200/students/580
Authorization: Bearer p9Mcpdxs7IdZbFNfRqLxbA
Content-Type: application/json
Accept: application/json

###
POST https://todu.mn/bs/lms/v1/token/email
Content-Type: application/json
Accept: application/json

{
    "email": "b222270827@must.edu.mn",
    "password": "123"
}

###
GET https://todu.mn/bs/lms/v1/courses/200/exams
Authorization: Bearer FoKqZEJV0d6AHw3sRlRLaw
Content-Type: application/json
Accept: application/json

###
GET https://todu.mn/bs/lms/v1/users/200/exams
Authorization: Bearer p9Mcpdxs7IdZbFNfRqLxbA
Content-Type: application/json
Accept: application/json
###
GET https://todu.mn/bs/lms/v1/courses/200/exams
Authorization: Bearer LgrtN81majHusm2itfWmGw
Content-Type: application/json
Accept: application/json

</file>
